/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.clinicamedica.telas;

import br.com.clinicamedica.classes.DAO.UsuarioDAO;
import br.com.clinicamedica.classes.Usuario;
import br.com.clinicamedica.conexao.Bd.BancoDeDados;
import javax.swing.JOptionPane;

/**
 * Tela Principal
 *
 * @author Cícero Higor &lt; chgs@icomp.ufam.edu.br&gt;
 * @version 1.12, 04/01/2017
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Usuario user = new Usuario();
    UsuarioDAO us = new UsuarioDAO();
    TelaFormularioMedico formMedico = new TelaFormularioMedico();
    TelaFormularioUsuario formUsuario = new TelaFormularioUsuario();
    TelaFormularioPaciente formPaciente = new TelaFormularioPaciente();
    TelaFormularioConsulta formConsulta = new TelaFormularioConsulta();
    TelaAgendaMedico telaAgendaMedico = new TelaAgendaMedico();
    TelaConfirmaConsulta telaAgenda = new TelaConfirmaConsulta();
    String aux;

    /**
     * Creates new form TelaAtendente
     *
     * @param user
     */
    public TelaPrincipal(String nome) {
        aux = nome;
        initComponents();
        jLabelNome.setText(nome);

    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelNome = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jButtonMedico = new javax.swing.JButton();
        jButtonPaciente = new javax.swing.JButton();
        jButtonUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonAgendamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAgendamedica = new javax.swing.JButton();
        jButtonAgendaAtendente = new javax.swing.JButton();
        jButtonAtualiza = new javax.swing.JButton();
        jLabelPlanoFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemMedico = new javax.swing.JMenuItem();
        jMenuItemCadastroUsuario = new javax.swing.JMenuItem();
        jMenuItemCadastroPaciente = new javax.swing.JMenuItem();
        jMenuItemCadastroConsultaPaciente = new javax.swing.JMenuItem();
        jMenuAgenda = new javax.swing.JMenu();
        jMenuItemAgendaMedico = new javax.swing.JMenuItem();
        jMenuItemAgendaAtendente = new javax.swing.JMenuItem();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuItemDeslogar = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(120, 20, 170, 20);

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin.setText("Usuário:");
        getContentPane().add(jLabelLogin);
        jLabelLogin.setBounds(30, 20, 90, 30);

        jButtonMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/CadMedicos.png"))); // NOI18N
        jButtonMedico.setToolTipText("Médico");
        jButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMedico);
        jButtonMedico.setBounds(40, 80, 90, 120);

        jButtonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/EditarPaciente.png"))); // NOI18N
        jButtonPaciente.setToolTipText("Paciente");
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPaciente);
        jButtonPaciente.setBounds(140, 80, 90, 120);

        jButtonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/check-user-icon.png"))); // NOI18N
        jButtonUsuario.setToolTipText("Usuário");
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUsuario);
        jButtonUsuario.setBounds(240, 80, 90, 120);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cadastro/Editar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 110, 20);

        jButtonAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/download.png"))); // NOI18N
        jButtonAgendamento.setToolTipText("Agendamento Paciente");
        jButtonAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendamento);
        jButtonAgendamento.setBounds(350, 80, 90, 120);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Agenda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 230, 60, 14);

        jButtonAgendamedica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/clipboard-add-black-interface-symbol_318-71670.png"))); // NOI18N
        jButtonAgendamedica.setToolTipText("Agenda médica");
        jButtonAgendamedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendamedicaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendamedica);
        jButtonAgendamedica.setBounds(40, 260, 90, 120);

        jButtonAgendaAtendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/dia_hora_3.png"))); // NOI18N
        jButtonAgendaAtendente.setToolTipText("Agenda Atendente");
        jButtonAgendaAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendaAtendente);
        jButtonAgendaAtendente.setBounds(150, 260, 90, 120);

        jButtonAtualiza.setText("Atualizar");
        jButtonAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualiza);
        jButtonAtualiza.setBounds(753, 10, 80, 20);

        jLabelPlanoFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/fondo-azul,-lineas-206492.jpg"))); // NOI18N
        getContentPane().add(jLabelPlanoFundo);
        jLabelPlanoFundo.setBounds(0, 0, 860, 430);

        jMenuCadastros.setText("Cadastros");

        jMenuItemMedico.setText("Médicos");
        jMenuItemMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemMedico);

        jMenuItemCadastroUsuario.setText("Usuários");
        jMenuItemCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastroUsuario);

        jMenuItemCadastroPaciente.setText("Pacientes");
        jMenuItemCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroPacienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastroPaciente);

        jMenuItemCadastroConsultaPaciente.setText("Consultas");
        jMenuItemCadastroConsultaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroConsultaPacienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastroConsultaPaciente);

        jMenuBar1.add(jMenuCadastros);

        jMenuAgenda.setText("Agenda");

        jMenuItemAgendaMedico.setText("Médico");
        jMenuItemAgendaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaMedicoActionPerformed(evt);
            }
        });
        jMenuAgenda.add(jMenuItemAgendaMedico);

        jMenuItemAgendaAtendente.setText("Atendente");
        jMenuItemAgendaAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaAtendenteActionPerformed(evt);
            }
        });
        jMenuAgenda.add(jMenuItemAgendaAtendente);

        jMenuBar1.add(jMenuAgenda);

        jMenuOpcoes.setText("Opções");

        jMenuItemDeslogar.setText("Deslogar");
        jMenuItemDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeslogarActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemDeslogar);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemSair);

        jMenuBar1.add(jMenuOpcoes);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(873, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeslogarActionPerformed
        BancoDeDados.desconecta();
        new TelaLoginUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemDeslogarActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicoActionPerformed
        if (us.controleAcessoUsuarioADministrador(jLabelNome.getText()) == true) {
            if (formMedico == null) {
                formMedico = new TelaFormularioMedico();
                formMedico.setVisible(true);
                formMedico.setResizable(false);
            } else {
                formMedico.setVisible(true);
                formMedico.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Administrador)");
        }
    }//GEN-LAST:event_jMenuItemMedicoActionPerformed

    private void jButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicoActionPerformed
        if (us.controleAcessoUsuarioADministrador(jLabelNome.getText()) == true) {
            if (formMedico == null) {
                formMedico = new TelaFormularioMedico();
                formMedico.setVisible(true);
                formMedico.setResizable(false);
            } else {
                formMedico.setVisible(true);
                formMedico.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Administrador)");
        }
    }//GEN-LAST:event_jButtonMedicoActionPerformed

    private void jMenuItemCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroUsuarioActionPerformed
        if (us.controleAcessoUsuarioADministrador(jLabelNome.getText()) == true) {
            if (formUsuario == null) {
                formUsuario = new TelaFormularioUsuario();
                formUsuario.setVisible(true);
                formUsuario.setResizable(false);
            } else {
                formUsuario.setVisible(true);
                formUsuario.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Administrador)");
        }
    }//GEN-LAST:event_jMenuItemCadastroUsuarioActionPerformed

    private void jMenuItemCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroPacienteActionPerformed
        // TODO add your handling code here:
        if (us.controleAcessoUsuarioAtendente(jLabelNome.getText()) == true) {
            if (formPaciente == null) {
                formPaciente = new TelaFormularioPaciente();
                formPaciente.setVisible(true);
                formPaciente.setResizable(false);
            } else {
                formPaciente.setVisible(true);
                formPaciente.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Atendente)");
        }
    }//GEN-LAST:event_jMenuItemCadastroPacienteActionPerformed

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        // TODO add your handling code here:
        if (us.controleAcessoUsuarioADministrador(jLabelNome.getText()) == true) {
            if (formUsuario == null) {
                formUsuario = new TelaFormularioUsuario();
                formUsuario.setVisible(true);
                formUsuario.setResizable(false);
            } else {
                formUsuario.setVisible(true);
                formUsuario.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Administrador)");
        }
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed
        if (us.controleAcessoUsuarioAtendente(jLabelNome.getText()) == true) {
            if (formPaciente == null) {
                formPaciente = new TelaFormularioPaciente();
                formPaciente.setVisible(true);
                formPaciente.setResizable(false);
            } else {
                formPaciente.setVisible(true);
                formPaciente.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Atendente)");
        }
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    private void jButtonAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendamentoActionPerformed
        // TODO add your handling code here:
        if (us.controleAcessoUsuarioAtendente(jLabelNome.getText()) == true) {
            if (formConsulta == null) {
                formConsulta = new TelaFormularioConsulta();
                formConsulta.setVisible(true);
                formConsulta.setResizable(false);
            } else {
                formConsulta.setVisible(true);
                formConsulta.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Atendente)");
        }
    }//GEN-LAST:event_jButtonAgendamentoActionPerformed

    private void jMenuItemCadastroConsultaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroConsultaPacienteActionPerformed
        // TODO add your handling code here:
        if (us.controleAcessoUsuarioAtendente(jLabelNome.getText()) == true) {
            if (formConsulta == null) {
                formConsulta = new TelaFormularioConsulta();
                formConsulta.setVisible(true);
                formConsulta.setResizable(false);
            } else {
                formConsulta.setVisible(true);
                formConsulta.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Atendente)");
        }
    }//GEN-LAST:event_jMenuItemCadastroConsultaPacienteActionPerformed

    private void jMenuItemAgendaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaMedicoActionPerformed
        // TODO add your handling code here:
        if (us.controleAcessoUsuarioMedico(jLabelNome.getText()) == true) {
            if (telaAgendaMedico == null) {
                telaAgendaMedico = new TelaAgendaMedico();
                telaAgendaMedico.setVisible(true);
                telaAgendaMedico.setResizable(false);
            } else {
                telaAgendaMedico.setVisible(true);
                telaAgendaMedico.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Médico)");
        }
    }//GEN-LAST:event_jMenuItemAgendaMedicoActionPerformed

    private void jButtonAgendamedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendamedicaActionPerformed

        if (us.controleAcessoUsuarioMedico(jLabelNome.getText()) == true) {
            if (telaAgendaMedico == null) {
                telaAgendaMedico = new TelaAgendaMedico();
                telaAgendaMedico.setVisible(true);
                telaAgendaMedico.setResizable(false);
            } else {
                telaAgendaMedico.setVisible(true);
                telaAgendaMedico.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Médico)");
        }

    }//GEN-LAST:event_jButtonAgendamedicaActionPerformed

    private void jButtonAgendaAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaAtendenteActionPerformed
        // TODO add your handling code here:
        if (us.controleAcessoUsuarioAtendente(jLabelNome.getText()) == true) {
            if (telaAgenda == null) {
                telaAgenda = new TelaConfirmaConsulta();
                telaAgenda.setVisible(true);
                telaAgenda.setResizable(false);
            } else {
                telaAgenda.setVisible(true);
                telaAgenda.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Atendente)");
        }
    }//GEN-LAST:event_jButtonAgendaAtendenteActionPerformed

    private void jMenuItemAgendaAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaAtendenteActionPerformed
        // TODO add your handling code here:
        if (us.controleAcessoUsuarioAtendente(jLabelNome.getText()) == true) {
            if (telaAgenda == null) {
                telaAgenda = new TelaConfirmaConsulta();
                telaAgenda.setVisible(true);
                telaAgenda.setResizable(false);
            } else {
                telaAgenda.setVisible(true);
                telaAgenda.setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão! (Atendente)");
        }
    }//GEN-LAST:event_jMenuItemAgendaAtendenteActionPerformed

    private void jButtonAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizaActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal(aux).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAtualizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendaAtendente;
    private javax.swing.JButton jButtonAgendamedica;
    private javax.swing.JButton jButtonAgendamento;
    private javax.swing.JButton jButtonAtualiza;
    private javax.swing.JButton jButtonMedico;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPlanoFundo;
    private javax.swing.JMenu jMenuAgenda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAgendaAtendente;
    private javax.swing.JMenuItem jMenuItemAgendaMedico;
    private javax.swing.JMenuItem jMenuItemCadastroConsultaPaciente;
    private javax.swing.JMenuItem jMenuItemCadastroPaciente;
    private javax.swing.JMenuItem jMenuItemCadastroUsuario;
    private javax.swing.JMenuItem jMenuItemDeslogar;
    private javax.swing.JMenuItem jMenuItemMedico;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuOpcoes;
    // End of variables declaration//GEN-END:variables
}
