/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.clinicamedica.telas;

import br.com.clinicamedica.classes.Consulta;
import br.com.clinicamedica.classes.DAO.ConsultaDAO;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 * Tela Confirma consulta
 *
 * @author Cícero Higor &lt; chgs@icomp.ufam.edu.br&gt;
 * @version 1.12, 04/01/2017
 */
public class TelaConfirmaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form TelaConfirmaConsulta
     */
    ConsultaDAO consultaDAO = new ConsultaDAO();
    Consulta consulta = new Consulta();

    String dtHoje;
    String status;

    public TelaConfirmaConsulta() {

        initComponents();
        Calendar data = Calendar.getInstance();
        java.util.Date d = data.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        dateFormat.format(d);

        dtHoje = dateFormat.format(d);
        status = "Aberto";

        listaTodos();

    }

    public void listaTodos() {

        Vector<Consulta> listaNomes = consultaDAO.consultar(dtHoje, status);
        Vector conjuntoLinhas = new Vector();

        for (Consulta con : listaNomes) {
            Vector linha = new Vector();
            linha.add(con.getIdConsulta());
            linha.add(con.getNomeMed());
            linha.add(con.getNomePac());
            linha.add(con.getDataConsulta());
            linha.add(con.getHorario());
            linha.add(con.getStatus());

            conjuntoLinhas.add(linha);

        }
        Vector conjuntoColunas = new Vector();
        conjuntoColunas.add("ID");
        conjuntoColunas.add("NOME MEDICO");
        conjuntoColunas.add("NOME PACIENTE");
        conjuntoColunas.add("DATA CONSULTA");
        conjuntoColunas.add("HORARIO");
        conjuntoColunas.add("STATUS");

        DefaultTableModel tabela = new DefaultTableModel(conjuntoLinhas, conjuntoColunas);

        jTableListaConsulta.setModel(tabela);

        jTableListaConsulta.getColumnModel().getColumn(0).setResizable(false);
        jTableListaConsulta.getColumnModel().getColumn(1).setResizable(false);
        jTableListaConsulta.getColumnModel().getColumn(2).setResizable(false);
        jTableListaConsulta.getColumnModel().getColumn(3).setResizable(false);
        jTableListaConsulta.getColumnModel().getColumn(4).setResizable(false);

        jTableListaConsulta.getTableHeader().setReorderingAllowed(false);
        jTableListaConsulta.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaConsulta = new javax.swing.JTable();
        jButtonRealizarAtendimento = new javax.swing.JButton();
        jButtonSelecionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(135, 206, 235));

        jTableListaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaConsulta);

        jButtonRealizarAtendimento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRealizarAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/confirmar.png"))); // NOI18N
        jButtonRealizarAtendimento.setToolTipText("Agendar");
        jButtonRealizarAtendimento.setEnabled(false);
        jButtonRealizarAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarAtendimentoActionPerformed(evt);
            }
        });

        jButtonSelecionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/Seleciona.png"))); // NOI18N
        jButtonSelecionar.setToolTipText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Realizar Atendimento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSelecionar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jButtonRealizarAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSelecionar)
                .addGap(18, 18, 18)
                .addComponent(jButtonRealizarAtendimento)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 460);

        setSize(new java.awt.Dimension(751, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableListaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaConsultaMouseClicked


    }//GEN-LAST:event_jTableListaConsultaMouseClicked

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        // TODO add your handling code here:
        if (jTableListaConsulta.getSelectedRow() >= 0) {
            String nome = "" + jTableListaConsulta.getModel().getValueAt(jTableListaConsulta.getSelectedRow(), 0);
            consultaDAO.acessaTabela(consulta, Integer.parseInt(nome));
            jButtonRealizarAtendimento.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Todos atendidos!");
            jButtonRealizarAtendimento.setEnabled(false);
            jButtonSelecionar.setEnabled(false);
            dispose();

        }
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jButtonRealizarAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarAtendimentoActionPerformed

        consulta.setStatus("Em atendimento");
        consultaDAO.alterar(consulta);
        listaTodos();


    }//GEN-LAST:event_jButtonRealizarAtendimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfirmaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRealizarAtendimento;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaConsulta;
    // End of variables declaration//GEN-END:variables
}
