/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.clinicamedica.telas;

import br.com.clinicamedica.classes.Consulta;
import br.com.clinicamedica.classes.DAO.ConsultaDAO;
import br.com.clinicamedica.classes.DAO.HorarioDAO;
import br.com.clinicamedica.classes.DAO.MedicoDAO;
import br.com.clinicamedica.classes.DAO.PacienteDAO;
import br.com.clinicamedica.classes.Horario;
import br.com.clinicamedica.classes.Medico;
import br.com.clinicamedica.classes.Paciente;
import br.com.clinicamedica.conexao.Bd.BancoDeDados;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 * Tela Formulário consulta
 *
 * @author Cícero Higor &lt; chgs@icomp.ufam.edu.br&gt;
 * @version 1.12, 04/01/2017
 */
public class TelaFormularioConsulta extends javax.swing.JFrame {

    PacienteDAO pacienteDAO = new PacienteDAO();
    Paciente paciente = new Paciente();
    ConsultaDAO consultaDAO = new ConsultaDAO();
    Consulta consulta = new Consulta();
    Medico medico = new Medico();
    MedicoDAO medicoDAO = new MedicoDAO();
    HorarioDAO horarioDAO = new HorarioDAO();
    /**
     * Creates new form TelaFormularioConsulta
     */
    Vector<Medico> listaNome = null;
    Vector<Horario> horario = null;

    public TelaFormularioConsulta() {
        initComponents();
        BancoDeDados.conecta();
        listaNome = medicoDAO.mostraTodosPersonal();
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel(listaNome);

        jComboBoxMedico.setModel(modeloCombo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomePaciente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaPaciente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonCadastraConsulta = new javax.swing.JButton();
        jButtonCancelaConsulta = new javax.swing.JButton();
        Especialidade = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxMedico = new javax.swing.JComboBox<>();
        jTextFieldEspecialidade = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooserData = new com.toedter.calendar.JDateChooser();
        jComboBoxHorario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(135, 206, 235));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Consulta");

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/busca.png"))); // NOI18N
        jButtonBuscar.setToolTipText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome Paciente:");

        jTextFieldNomePaciente.setEditable(false);
        jTextFieldNomePaciente.setEnabled(false);

        jTableListaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaPaciente);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nome Médico:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Observações");

        jButtonCadastraConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/confirmar.png"))); // NOI18N
        jButtonCadastraConsulta.setToolTipText("Cadastra Consulta");
        jButtonCadastraConsulta.setEnabled(false);
        jButtonCadastraConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraConsultaActionPerformed(evt);
            }
        });

        jButtonCancelaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/cancela.png"))); // NOI18N
        jButtonCancelaConsulta.setToolTipText("Cancela Consulta");
        jButtonCancelaConsulta.setEnabled(false);
        jButtonCancelaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelaConsultaActionPerformed(evt);
            }
        });

        Especialidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Especialidade.setText("Especialidade");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Horário ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Data");

        jComboBoxMedico.setEnabled(false);
        jComboBoxMedico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMedicoItemStateChanged(evt);
            }
        });
        jComboBoxMedico.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jComboBoxMedicoMouseWheelMoved(evt);
            }
        });
        jComboBoxMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMedicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxMedicoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxMedicoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBoxMedicoMouseReleased(evt);
            }
        });

        jTextFieldEspecialidade.setEditable(false);
        jTextFieldEspecialidade.setEnabled(false);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(135, 206, 235));
        jTextField1.setForeground(new java.awt.Color(135, 206, 235));
        jTextField1.setCaretColor(new java.awt.Color(135, 206, 235));
        jTextField1.setDisabledTextColor(new java.awt.Color(135, 206, 235));
        jTextField1.setOpaque(false);
        jTextField1.setRequestFocusEnabled(false);
        jTextField1.setSelectedTextColor(new java.awt.Color(135, 206, 235));
        jTextField1.setSelectionColor(new java.awt.Color(135, 206, 235));

        jTextAreaObs.setColumns(20);
        jTextAreaObs.setRows(5);
        jTextAreaObs.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaObs);

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Pesquisa Nome:");

        jDateChooserData.setEnabled(false);

        jComboBoxHorario.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(295, 295, 295)
                        .addComponent(Especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(335, 335, 335))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(119, 119, 119)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateChooserData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextFieldNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(287, 287, 287))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jButtonCadastraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jButtonCancelaConsulta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Especialidade, jLabel2, jLabel3, jLabel4});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCadastraConsulta, jButtonCancelaConsulta});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Especialidade)
                    .addComponent(jComboBoxMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel4)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastraConsulta)
                    .addComponent(jButtonCancelaConsulta))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Especialidade, jLabel2, jLabel3, jLabel4});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCadastraConsulta, jButtonCancelaConsulta});

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 570);

        setSize(new java.awt.Dimension(846, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        jTextFieldPesquisa.requestFocus();
        if (jTextFieldPesquisa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Vazio");
            jTableListaPaciente.setToolTipText(" ");
            jTextFieldNomePaciente.setText("");

        } else {

            Vector<Paciente> listaNomes = pacienteDAO.consultar(jTextFieldPesquisa.getText());
            Vector conjuntoLinhas = new Vector();

            for (Paciente pacien : listaNomes) {
                Vector linha = new Vector();

                linha.add(pacien.getNome());
                linha.add(pacien.getRg());
                linha.add(pacien.getCpf());
                linha.add(pacien.getCelular());
                linha.add(pacien.getTelefone());
                linha.add(pacien.getNasc());
                conjuntoLinhas.add(linha);

            }
            Vector conjuntoColunas = new Vector();
            conjuntoColunas.add("NOME");
            conjuntoColunas.add("RG");
            conjuntoColunas.add("CPF");
            conjuntoColunas.add("CELULAR");
            conjuntoColunas.add("TELEFONE");
            conjuntoColunas.add("NASCIMENTO");

            DefaultTableModel tabela = new DefaultTableModel(conjuntoLinhas, conjuntoColunas);

            jTableListaPaciente.setModel(tabela);

            jTableListaPaciente.getColumnModel().getColumn(0).setResizable(false);
            jTableListaPaciente.getColumnModel().getColumn(1).setResizable(false);
            jTableListaPaciente.getColumnModel().getColumn(2).setResizable(false);
            jTableListaPaciente.getColumnModel().getColumn(3).setResizable(false);
            jTableListaPaciente.getColumnModel().getColumn(4).setResizable(false);
            jTableListaPaciente.getColumnModel().getColumn(5).setResizable(false);
            jTableListaPaciente.getTableHeader().setReorderingAllowed(false);
            jTableListaPaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jComboBoxMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMedicoMouseClicked

        if (jComboBoxMedico.getSelectedIndex() >= 0) {
            String nome = "" + jComboBoxMedico.getModel().getSelectedItem();
            jTextField1.setText(medico.getNome());
            jTextFieldEspecialidade.setText(medico.getEspecialidade());
            medicoDAO.acessaTabela(medico, nome);

        }

    }//GEN-LAST:event_jComboBoxMedicoMouseClicked

    private void jComboBoxMedicoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMedicoMouseReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_jComboBoxMedicoMouseReleased

    private void jComboBoxMedicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMedicoMousePressed
        // TODO add your handling code here:
        if (jComboBoxMedico.getSelectedIndex() > 0) {
            String nome = "" + jComboBoxMedico.getModel().getSelectedItem();
            medicoDAO.acessaTabela(medico, nome);

            jTextFieldEspecialidade.setText(medico.getEspecialidade());
        }
    }//GEN-LAST:event_jComboBoxMedicoMousePressed

    private void jComboBoxMedicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMedicoMouseEntered
        // TODO add your handling code here:

        if (jComboBoxMedico.getSelectedIndex() > 0) {
            String nome = "" + jComboBoxMedico.getModel().getSelectedItem();
            medicoDAO.acessaTabela(medico, nome);

            jTextFieldEspecialidade.setText(medico.getEspecialidade());
        }
    }//GEN-LAST:event_jComboBoxMedicoMouseEntered

    private void jComboBoxMedicoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jComboBoxMedicoMouseWheelMoved
        // TODO add your handling code here:
        if (jComboBoxMedico.getSelectedIndex() > 0) {
            String nome = "" + jComboBoxMedico.getModel().getSelectedItem();
            medicoDAO.acessaTabela(medico, nome);

            jTextFieldEspecialidade.setText(medico.getEspecialidade());
        }
    }//GEN-LAST:event_jComboBoxMedicoMouseWheelMoved

    private void jComboBoxMedicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMedicoItemStateChanged

        String nome = "" + jComboBoxMedico.getModel().getSelectedItem();
        medicoDAO.acessaTabela(medico, nome);

        jTextFieldEspecialidade.setText(medico.getEspecialidade());
        jTextField1.setText(medico.getNome());

        horario = horarioDAO.mostraTodosHorario(medico.getIdMedico());

        DefaultComboBoxModel hora = new DefaultComboBoxModel(horario);
        jComboBoxHorario.setModel(hora);


    }//GEN-LAST:event_jComboBoxMedicoItemStateChanged

    private void jTableListaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaPacienteMouseClicked
        // TODO add your handling code here:

        if (jTableListaPaciente.getSelectedRow() >= 0) {
            String nome = "" + jTableListaPaciente.getModel().getValueAt(jTableListaPaciente.getSelectedRow(), 0);
            pacienteDAO.acessaTabela(paciente, nome);
            jTextFieldNomePaciente.setText(paciente.getNome());
            jComboBoxHorario.setSelectedItem("");
            jComboBoxHorario.setEnabled(true);
            jComboBoxMedico.setEnabled(true);
            jDateChooserData.setEnabled(true);
            jButtonCadastraConsulta.setEnabled(true);
            jButtonCancelaConsulta.setEnabled(true);
            jTextAreaObs.setEnabled(true);
        }
    }//GEN-LAST:event_jTableListaPacienteMouseClicked


    private void jButtonCadastraConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraConsultaActionPerformed
        // TODO add your handling code here:

        if (jComboBoxMedico.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione o médico");
        } else if (jTextFieldNomePaciente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o usuario");
        } else if (jComboBoxHorario.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "informe o horário!");

        } else if (jDateChooserData.getDate() == null) {

            JOptionPane.showMessageDialog(null, "informe a data!");
        } else if (jTextAreaObs.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "informe a observacao!");

        } else if (jComboBoxMedico.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Informe o médico");
        } else {
            consulta.setHorario((String) jComboBoxHorario.getSelectedItem());
            consulta.setNomePac(jTextFieldNomePaciente.getText());
            consulta.setNomeMed(jTextField1.getText());
            consulta.setObservacoes(jTextAreaObs.getText());
            consulta.setDataConsulta(jDateChooserData.getDate());
            consulta.setStatus("Aberto");
            consultaDAO.controleAgendamento(consulta, medico.getIdMedico());

            dispose();

        }


    }//GEN-LAST:event_jButtonCadastraConsultaActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonCancelaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelaConsultaActionPerformed
        jTextFieldNomePaciente.setText("");
        jDateChooserData.setToolTipText("");
        jComboBoxHorario.setSelectedItem("");
        jTextFieldNomePaciente.setText("");
        jTextFieldPesquisa.setText("");
        jComboBoxMedico.setSelectedIndex(-1);
        jTextFieldEspecialidade.setText("");
        jTextAreaObs.setText("");
        jComboBoxHorario.setEnabled(false);
        jDateChooserData.setEnabled(false);
        jComboBoxMedico.setEnabled(false);
        jTextAreaObs.setEnabled(false);
        jButtonCadastraConsulta.setEnabled(false);
        jButtonCancelaConsulta.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelaConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFormularioConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Especialidade;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCadastraConsulta;
    private javax.swing.JButton jButtonCancelaConsulta;
    private javax.swing.JComboBox<String> jComboBoxHorario;
    private javax.swing.JComboBox<String> jComboBoxMedico;
    private com.toedter.calendar.JDateChooser jDateChooserData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListaPaciente;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldEspecialidade;
    private javax.swing.JTextField jTextFieldNomePaciente;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables

}
