/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.clinicamedica.telas;

import br.com.clinicamedica.conexao.Bd.BancoDeDados;
import br.com.clinicamedica.classes.DAO.PacienteDAO;
import br.com.clinicamedica.classes.Paciente;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 * Tela Cadastrar/Editar/excluir Paciente
 *
 * @author Cícero Higor &lt; chgs@icomp.ufam.edu.br&gt;
 * @version 1.12, 04/01/2017
 */
public class TelaFormularioPaciente extends javax.swing.JFrame {

    PacienteDAO pacienteDAO = new PacienteDAO();
    Paciente paciente = new Paciente();
    BancoDeDados bd = new BancoDeDados();
    int flag = 0;

    /**
     * Creates new form TelaFormularioMedico
     */
    public TelaFormularioPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFielCpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaPaciente = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldIdPaciente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(135, 206, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Paciente");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        jTextFieldNome.setEnabled(false);

        try {
            jFormattedTextFielCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFielCpf.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Rg");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cpf");

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRg.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Email");

        jTextFieldEmail.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Celular");

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Telefone");

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setEnabled(false);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/Salva usuario.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar paciente");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/Novo usuario.jpg"))); // NOI18N
        jButtonNovo.setToolTipText("Novo paciente");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/cancela.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancela");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/deleta.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Excluir paciente");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/edita usuario.jpg"))); // NOI18N
        jButtonEditar.setToolTipText("Editar paciente");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jTableListaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListaPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableListaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaPaciente);

        jButtonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/busca.png"))); // NOI18N
        jButtonPesquisa.setToolTipText("Busca");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("ID PACIENTE");

        jTextFieldIdPaciente.setEditable(false);
        jTextFieldIdPaciente.setEnabled(false);
        jTextFieldIdPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdPacienteActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Endereco");

        jTextFieldEndereco.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nascimento");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Cep");

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCep.setEnabled(false);

        jDateChooser1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jFormattedTextFielCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel9)))
                                                    .addGap(18, 18, 18)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextFieldPesquisa)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonPesquisa)
                                            .addGap(63, 63, 63))
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(3, 3, 3))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel4, jLabel6, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancelar, jButtonEditar, jButtonExcluir, jButtonNovo, jButtonSalvar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDateChooser1, jFormattedTextFielCpf});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jFormattedTextFielCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel4, jLabel6, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jFormattedTextFieldCelular, jFormattedTextFieldRg, jFormattedTextFieldTelefone});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCancelar, jButtonEditar, jButtonExcluir, jButtonNovo, jButtonSalvar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDateChooser1, jFormattedTextFielCpf});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(894, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    private static final Pattern pattern = Pattern.compile(EMAIL_PATTERN, Pattern.CASE_INSENSITIVE);

    public static boolean validarEmail(String email) {
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        jTextFieldNome.requestFocus();
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jFormattedTextFielCpf.setEnabled(false);
        jFormattedTextFieldCelular.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(true);
        jDateChooser1.setEnabled(false);
        jFormattedTextFieldCep.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (flag == 1) {
            if (jTextFieldNome.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o NOME!");
            } else if (jDateChooser1.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Informe a data de nascimento!");
            } else if (jFormattedTextFieldRg.getText().equalsIgnoreCase("       - ")) {
                JOptionPane.showMessageDialog(null, "Informe o RG!");
            } else if (jFormattedTextFielCpf.getText().equalsIgnoreCase("   .   .   -  ")) {
                JOptionPane.showMessageDialog(null, "Informe o CPF!");
            } else if (jFormattedTextFieldTelefone.getText().equalsIgnoreCase("    -    ")) {
                JOptionPane.showMessageDialog(null, "Informe o Telefone!");
            } else if (jFormattedTextFieldCelular.getText().equalsIgnoreCase("     -    ")) {
                JOptionPane.showMessageDialog(null, "Informe o Celular!");
            } else if (jFormattedTextFieldCep.getText().equalsIgnoreCase("     -   ")) {
                JOptionPane.showMessageDialog(null, "Informe o Cep!");
            } else if (jTextFieldEndereco.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Endereco!");
            } else if (jTextFieldEmail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o EMAIL!");
            } else if (validarEmail(jTextFieldEmail.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Email Inválido!");
            } else {
                paciente.setNome(jTextFieldNome.getText());
                paciente.setNasc(jDateChooser1.getDate());
                paciente.setRg(jFormattedTextFieldRg.getText());
                paciente.setCpf(jFormattedTextFielCpf.getText());
                paciente.setTelefone(jFormattedTextFieldTelefone.getText());
                paciente.setCelular(jFormattedTextFieldCelular.getText());
                paciente.setCep(jFormattedTextFieldCep.getText());
                paciente.setEndereco(jTextFieldEndereco.getText());
                paciente.setEmail(jTextFieldEmail.getText());

                pacienteDAO.controleAcesso(paciente);
                TelaFormularioPaciente tela = new TelaFormularioPaciente();
                tela.setVisible(true);
                dispose();
            }
        } else if (jTextFieldNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o nome!");
        } else if (jFormattedTextFieldTelefone.getText().equalsIgnoreCase("    -    ")) {
            JOptionPane.showMessageDialog(null, "Informe o Telefone!");
        } else if (jFormattedTextFieldCelular.getText().equalsIgnoreCase("     -    ")) {
            JOptionPane.showMessageDialog(null, "Informe o Celular!");
        } else if (jFormattedTextFieldCep.getText().equalsIgnoreCase("     -   ")) {
            JOptionPane.showMessageDialog(null, "Informe o Cep!");
        } else if (jTextFieldEndereco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Endereco!");
        } else if (jTextFieldEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Email!");
        } else if (validarEmail(jTextFieldEmail.getText()) == true) {

            paciente.setIdPaciente(Integer.parseInt(jTextFieldIdPaciente.getText()));
            paciente.setNome(jTextFieldNome.getText());
            paciente.setRg(jFormattedTextFieldRg.getText());
            paciente.setCpf(jFormattedTextFielCpf.getText());
            paciente.setEmail(jTextFieldEmail.getText());
            paciente.setTelefone(jFormattedTextFieldTelefone.getText());
            paciente.setCelular(jFormattedTextFieldCelular.getText());
            paciente.setEndereco(jTextFieldEndereco.getText());
            paciente.setCep(jFormattedTextFieldCep.getText());
            paciente.setNasc(jDateChooser1.getDate());
            pacienteDAO.alterar(paciente);

            jTextFieldIdPaciente.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldNome.setText("");
            jTextFieldEmail.setText("");

            jFormattedTextFielCpf.setText("");
            jFormattedTextFieldCelular.setText("");
            jFormattedTextFieldRg.setText("");
            jFormattedTextFieldTelefone.setText("");
            jFormattedTextFieldCep.setText("");
            jDateChooser1.setEnabled(false);
            jFormattedTextFieldCep.setEnabled(false);

            jTextFieldNome.setEnabled(false);
            jTextFieldEmail.setEnabled(false);
            jTextFieldEndereco.setEnabled(false);

            jFormattedTextFielCpf.setEnabled(false);
            jFormattedTextFieldCelular.setEnabled(false);
            jFormattedTextFieldRg.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);

            jButtonCancelar.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            TelaFormularioPaciente tela = new TelaFormularioPaciente();
            tela.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Email inválido");
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jTextFieldNome.requestFocus();
        flag = 1;
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");

        jFormattedTextFieldCep.setText("");
        jFormattedTextFielCpf.setText("");
        jFormattedTextFieldCelular.setText("");
        jTextFieldEndereco.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelefone.setText("");

        jDateChooser1.setEnabled(true);//verificar
        jTextFieldEndereco.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldEmail.setEnabled(true);

        jFormattedTextFielCpf.setEnabled(true);
        jFormattedTextFieldCelular.setEnabled(true);
        jFormattedTextFieldCep.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);

        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);

        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed


    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        paciente.setBusca(jTextFieldPesquisa.getText());

        if (jTextFieldPesquisa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Vazio!");
            listaNome();
            jTextFieldNome.setText("");
            jTextFieldEmail.setText("");

            jFormattedTextFielCpf.setText("");
            jFormattedTextFieldCelular.setText("");

            jTextFieldEndereco.setText("");
            jFormattedTextFieldRg.setText("");
            jFormattedTextFieldTelefone.setText("");
            jFormattedTextFieldCep.setText("");
            jTextFieldIdPaciente.setText("");

            jDateChooser1.setEnabled(false);
            jFormattedTextFieldCep.setEnabled(false);

            jTextFieldNome.setEnabled(false);
            jTextFieldEmail.setEnabled(false);

            jFormattedTextFielCpf.setEnabled(false);
            jFormattedTextFieldCelular.setEnabled(false);
            jTextFieldEndereco.setEnabled(false);

            jFormattedTextFieldRg.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);

            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);

        } else {
            Vector<Paciente> listaNomes = pacienteDAO.consultar(jTextFieldPesquisa.getText());
            Vector conjuntoLinhas = new Vector();

            for (Paciente pacien : listaNomes) {
                Vector linha = new Vector();

                linha.add(pacien.getNome());
                linha.add(pacien.getRg());
                linha.add(pacien.getCpf());
                linha.add(pacien.getCelular());
                linha.add(pacien.getTelefone());
                linha.add(pacien.getNasc());
                conjuntoLinhas.add(linha);

            }
            Vector conjuntoColunas = new Vector();
            conjuntoColunas.add("NOME");
            conjuntoColunas.add("RG");
            conjuntoColunas.add("CPF");
            conjuntoColunas.add("CELULAR");
            conjuntoColunas.add("TELEFONE");
            conjuntoColunas.add("NASCIMENTO");

            DefaultTableModel tabela = new DefaultTableModel(conjuntoLinhas, conjuntoColunas);

            jTableListaPaciente.setModel(tabela);

            jTableListaPaciente.getColumnModel().getColumn(0).setResizable(false);
            jTableListaPaciente.getColumnModel().getColumn(1).setResizable(false);
            jTableListaPaciente.getColumnModel().getColumn(2).setResizable(false);
            jTableListaPaciente.getColumnModel().getColumn(3).setResizable(false);
            jTableListaPaciente.getColumnModel().getColumn(4).setResizable(false);
            jTableListaPaciente.getColumnModel().getColumn(5).setResizable(false);
            jTableListaPaciente.getTableHeader().setReorderingAllowed(false);
            jTableListaPaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        }


    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    public void listaNome() {
        Vector<Paciente> listaNomes = pacienteDAO.mostrarTodos();
        Vector conjuntoLinhas = new Vector();

        for (Paciente pacien : listaNomes) {
            Vector linha = new Vector();

            linha.add(pacien.getNome());
            linha.add(pacien.getRg());
            linha.add(pacien.getCpf());
            linha.add(pacien.getCelular());
            linha.add(pacien.getTelefone());
            linha.add(pacien.getNasc());

            conjuntoLinhas.add(linha);

        }
        Vector conjuntoColunas = new Vector();
        conjuntoColunas.add("NOME");
        conjuntoColunas.add("RG");
        conjuntoColunas.add("CPF");
        conjuntoColunas.add("CELULAR");
        conjuntoColunas.add("TELEFONE");
        conjuntoColunas.add("NASCIMENTO");

        DefaultTableModel tabela = new DefaultTableModel(conjuntoLinhas, conjuntoColunas);

        jTableListaPaciente.setModel(tabela);

        jTableListaPaciente.getColumnModel().getColumn(0).setResizable(false);
        jTableListaPaciente.getColumnModel().getColumn(1).setResizable(false);
        jTableListaPaciente.getColumnModel().getColumn(2).setResizable(false);
        jTableListaPaciente.getColumnModel().getColumn(3).setResizable(false);
        jTableListaPaciente.getColumnModel().getColumn(4).setResizable(false);
        jTableListaPaciente.getColumnModel().getColumn(5).setResizable(false);
        jTableListaPaciente.getTableHeader().setReorderingAllowed(false);
        jTableListaPaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }


    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        jTextFieldIdPaciente.setText("");
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jFormattedTextFielCpf.setText("");
        jFormattedTextFieldCelular.setText("");
        jTextFieldEndereco.setText("");

        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelefone.setText("");

        jFormattedTextFieldCep.setText("");

        jDateChooser1.setEnabled(false);
        jFormattedTextFieldCep.setEnabled(false);

        jTextFieldEndereco.setEnabled(false);
        jTextFieldNome.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jFormattedTextFielCpf.setEnabled(false);
        jFormattedTextFieldCelular.setEnabled(false);

        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);

        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);


    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldIdPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdPacienteActionPerformed


    }//GEN-LAST:event_jTextFieldIdPacienteActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        String message = "Voce deseja realmente  excluir?";

        int reply = JOptionPane.showConfirmDialog(null, message, "", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            paciente.setIdPaciente(Integer.parseInt(jTextFieldIdPaciente.getText()));
            pacienteDAO.excluir(paciente);

            jTextFieldIdPaciente.setText("");
            jTextFieldNome.setText("");
            jTextFieldEmail.setText("");

            jFormattedTextFielCpf.setText("");
            jFormattedTextFieldCelular.setText("");
            jTextFieldEndereco.setText("");

            jFormattedTextFieldRg.setText("");
            jFormattedTextFieldTelefone.setText("");

            jFormattedTextFieldCep.setText("");
            jDateChooser1.setEnabled(false);
            jFormattedTextFieldCep.setEnabled(false);

            jTextFieldEndereco.setEnabled(false);
            jTextFieldNome.setEnabled(false);
            jTextFieldEmail.setEnabled(false);

            jFormattedTextFielCpf.setEnabled(false);
            jFormattedTextFieldCelular.setEnabled(false);

            jFormattedTextFieldRg.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);

            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            TelaFormularioPaciente tela = new TelaFormularioPaciente();
            tela.setVisible(true);
            dispose();

        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableListaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaPacienteMouseClicked
        if (jTableListaPaciente.getSelectedRow() >= 0) {
            String nome = "" + jTableListaPaciente.getModel().getValueAt(jTableListaPaciente.getSelectedRow(), 0);
            pacienteDAO.acessaTabela(paciente, nome);
            jTextFieldIdPaciente.setText(String.valueOf(paciente.getIdPaciente()));
            jTextFieldNome.setText(paciente.getNome());

            jDateChooser1.setDate(paciente.getNasc());
            jFormattedTextFieldRg.setText(paciente.getRg());
            jFormattedTextFielCpf.setText(paciente.getCpf());
            jFormattedTextFieldTelefone.setText(paciente.getTelefone());
            jFormattedTextFieldCelular.setText(paciente.getCelular());
            jFormattedTextFieldCep.setText(paciente.getCep());

            jTextFieldEndereco.setText(paciente.getEndereco());

            jTextFieldEmail.setText(paciente.getEmail());

            jButtonEditar.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonSalvar.setEnabled(false);
        }

    }//GEN-LAST:event_jTableListaPacienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFormularioPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextFielCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaPaciente;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldIdPaciente;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
