/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.clinicamedica.telas;

import br.com.clinicamedica.conexao.Bd.BancoDeDados;
import br.com.clinicamedica.classes.DAO.MedicoDAO;
import br.com.clinicamedica.classes.Medico;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 * Tela Cadastrar/Editar/excluir médico
 *
 * @author Cícero Higor &lt; chgs@icomp.ufam.edu.br&gt;
 * @version 1.12, 04/01/2017
 */
public class TelaFormularioMedico extends javax.swing.JFrame {

    MedicoDAO medicoDAO = new MedicoDAO();
    Medico medico = new Medico();
    BancoDeDados bd = new BancoDeDados();
    int flag = 0;

    /**
     * Creates new form TelaFormularioMedico
     */
    public TelaFormularioMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFielCpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxEspecialidade = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextFieldCrm = new javax.swing.JFormattedTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaMedico = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldidMedico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(135, 206, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Médico");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        jTextFieldNome.setEnabled(false);

        try {
            jFormattedTextFielCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFielCpf.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Rg");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cpf");

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRg.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Especialidade");

        jComboBoxEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acupuntura", "Alergia e Imunologia", "Anestesiologia", "Angiologia", "Cancerologia", "Cardiologia", "Dermatologia", "Endocrinologia e Metabologia", "Gastroenterologia", "Geriatria", "Ginecologia e obstetrícia", "Hematologia e Hemoterapia", "Homeopatia", "Infectologia", "Mastologia", "Nefrologia", "Neurologia", "Nutrologia", "Oftalmologia", "Ortopedia e Traumatologia", "Otorrinolaringologia", "Patologia", "Pediatria", "Pneumologia", "Psiquiatria", "Reumatologia", "Urulogia" }));
        jComboBoxEspecialidade.setSelectedIndex(-1);
        jComboBoxEspecialidade.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Email");

        jTextFieldEmail.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Celular");

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Telefone");

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("CRM");

        try {
            jFormattedTextFieldCrm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCrm.setEnabled(false);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/Salva usuario.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar médico");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/Novo usuario.jpg"))); // NOI18N
        jButtonNovo.setToolTipText("Novo médico");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/cancela.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancela");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/deleta.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/edita usuario.jpg"))); // NOI18N
        jButtonEditar.setToolTipText("Editar médico");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jTableListaMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListaMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableListaMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaMedicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaMedico);

        jButtonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/clinicamedica/imagens/busca.png"))); // NOI18N
        jButtonPesquisa.setToolTipText("Busca");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("ID MEDICO");

        jTextFieldidMedico.setEditable(false);
        jTextFieldidMedico.setEnabled(false);
        jTextFieldidMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldidMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jFormattedTextFieldCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBoxEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldNome)
                                        .addComponent(jTextFieldEmail)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jFormattedTextFielCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel2, jLabel4, jLabel6, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFormattedTextFieldCelular, jFormattedTextFieldCrm, jFormattedTextFieldTelefone});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancelar, jButtonEditar, jButtonExcluir, jButtonNovo, jButtonSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldidMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jFormattedTextFieldCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jFormattedTextFielCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel2, jLabel4, jLabel6, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldEmail, jTextFieldNome});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jFormattedTextFieldCelular, jFormattedTextFieldCrm, jFormattedTextFieldRg, jFormattedTextFieldTelefone});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel5, jLabel8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCancelar, jButtonEditar, jButtonExcluir, jButtonNovo, jButtonSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(851, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    private static final Pattern pattern = Pattern.compile(EMAIL_PATTERN, Pattern.CASE_INSENSITIVE);

    public static boolean validarEmail(String email) {
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jTextFieldEmail.setEnabled(true);

        jFormattedTextFielCpf.setEnabled(false);
        jFormattedTextFieldCelular.setEnabled(true);
        jFormattedTextFieldCrm.setEnabled(false);
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(true);

        jComboBoxEspecialidade.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (flag == 1) {
            if (jFormattedTextFieldCrm.getText().equalsIgnoreCase("          - ")) {
                JOptionPane.showMessageDialog(null, "Informe o CRM!");
            } else if (jComboBoxEspecialidade.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Informe a ESPECIALIDADE");
            } else if (jTextFieldNome.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o NOME!");
            } else if (jFormattedTextFielCpf.getText().equalsIgnoreCase("   .   .   -  ")) {
                JOptionPane.showMessageDialog(null, "Informe o CPF!");
            } else if (jFormattedTextFieldRg.getText().equalsIgnoreCase("       - ")) {
                JOptionPane.showMessageDialog(null, "Informe o RG!");
            } else if (jTextFieldEmail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o EMAIL!");
            } else if (jFormattedTextFieldCelular.getText().equalsIgnoreCase("     -    ")) {
                JOptionPane.showMessageDialog(null, "Informe o Celular!");
            } else if (jFormattedTextFieldTelefone.getText().equalsIgnoreCase("    -    ")) {
                JOptionPane.showMessageDialog(null, "Informe o Telefone!");
            } else if (validarEmail(jTextFieldEmail.getText()) == false) {
                JOptionPane.showMessageDialog(null, "Email Inválido");
            } else {
                medico.setCrm(jFormattedTextFieldCrm.getText());
                medico.setEspecialidade((String) jComboBoxEspecialidade.getSelectedItem());
                medico.setNome(jTextFieldNome.getText());
                medico.setCpf(jFormattedTextFielCpf.getText());
                medico.setRg(jFormattedTextFieldRg.getText());
                medico.setCelular(jFormattedTextFieldCelular.getText());
                medico.setEmail(jTextFieldEmail.getText());
                medico.setTelefone(jFormattedTextFieldTelefone.getText());

                medicoDAO.controleAcesso(medico);
                TelaFormularioMedico tela = new TelaFormularioMedico();
                tela.setVisible(true);
                dispose();

            }
        } else if (jTextFieldNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o NOME!");
        } else if (jComboBoxEspecialidade.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Informe a especialidade!");
        } else if (jFormattedTextFielCpf.getText().equalsIgnoreCase("   .   .   -  ")) {
            JOptionPane.showMessageDialog(null, "Informe o CPF!");
        } else if (jFormattedTextFieldRg.getText().equalsIgnoreCase("       - ")) {
            JOptionPane.showMessageDialog(null, "Informe o RG!");
        } else if (jTextFieldEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o EMAIL!");
        } else if (jFormattedTextFieldCelular.getText().equalsIgnoreCase("     -    ")) {
            JOptionPane.showMessageDialog(null, "Informe o Celular!");
        } else if (jFormattedTextFieldTelefone.getText().equalsIgnoreCase("    -    ")) {
            JOptionPane.showMessageDialog(null, "Informe o Telefone!");
        } else if (validarEmail(jTextFieldEmail.getText()) == true) {
            medico.setIdMedico(Integer.parseInt(jTextFieldidMedico.getText()));
            medico.setCrm(jFormattedTextFieldCrm.getText());
            medico.setNome(jTextFieldNome.getText());
            medico.setCpf(jFormattedTextFielCpf.getText());
            medico.setRg(jFormattedTextFieldRg.getText());

            medico.setEmail(jTextFieldEmail.getText());
            medico.setTelefone(jFormattedTextFieldTelefone.getText());
            medico.setCelular(jFormattedTextFieldCelular.getText());

            medico.setEspecialidade((String) jComboBoxEspecialidade.getSelectedItem());
            medicoDAO.alterar(medico);

            jTextFieldidMedico.setText("");
            jTextFieldNome.setText("");
            jTextFieldEmail.setText("");

            jFormattedTextFielCpf.setText("");
            jFormattedTextFieldCelular.setText("");
            jFormattedTextFieldCrm.setText("");
            jFormattedTextFieldRg.setText("");
            jFormattedTextFieldTelefone.setText("");

            jComboBoxEspecialidade.setSelectedIndex(-1);
            jTextFieldNome.setEnabled(false);
            jTextFieldEmail.setEnabled(false);

            jFormattedTextFielCpf.setEnabled(false);
            jFormattedTextFieldCelular.setEnabled(false);
            jFormattedTextFieldCrm.setEnabled(false);
            jFormattedTextFieldRg.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);

            jComboBoxEspecialidade.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            TelaFormularioMedico tela = new TelaFormularioMedico();
            tela.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Email Inválido");
        }


    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jTextFieldPesquisa.setText("");
        jFormattedTextFielCpf.setText("");
        jFormattedTextFieldCelular.setText("");
        jFormattedTextFieldCrm.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelefone.setText("");

        jTextFieldNome.setEnabled(true);
        jTextFieldEmail.setEnabled(true);

        jFormattedTextFielCpf.setEnabled(true);
        jFormattedTextFieldCelular.setEnabled(true);
        jFormattedTextFieldCrm.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);

        jComboBoxEspecialidade.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);

        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed


    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        medico.setBusca(jTextFieldPesquisa.getText());

        if (jTextFieldPesquisa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Vazio!");
            listaNome();
            jTextFieldNome.setText("");
            jTextFieldEmail.setText("");

            jFormattedTextFielCpf.setText("");
            jFormattedTextFieldCelular.setText("");
            jFormattedTextFieldCrm.setText("");
            jFormattedTextFieldRg.setText("");
            jFormattedTextFieldTelefone.setText("");

            jTextFieldidMedico.setText("");
            jComboBoxEspecialidade.setSelectedIndex(-1);
            jTextFieldNome.setEnabled(false);
            jTextFieldEmail.setEnabled(false);

            jFormattedTextFielCpf.setEnabled(false);
            jFormattedTextFieldCelular.setEnabled(false);
            jFormattedTextFieldCrm.setEnabled(false);
            jFormattedTextFieldRg.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);

            jComboBoxEspecialidade.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);

        } else {
            Vector<Medico> listaNomes = medicoDAO.consultar(jTextFieldPesquisa.getText());
            Vector conjuntoLinhas = new Vector();

            for (Medico md : listaNomes) {
                Vector linha = new Vector();

                linha.add(md.getNome());
                linha.add(md.getCrm());
                linha.add(md.getEspecialidade());

                conjuntoLinhas.add(linha);

            }
            Vector conjuntoColunas = new Vector();
            conjuntoColunas.add("NOME");
            conjuntoColunas.add("CRM");
            conjuntoColunas.add("ESPECIALIDADE");

            DefaultTableModel tabela = new DefaultTableModel(conjuntoLinhas, conjuntoColunas);

            jTableListaMedico.setModel(tabela);

            jTableListaMedico.getColumnModel().getColumn(0).setResizable(false);
            jTableListaMedico.getColumnModel().getColumn(1).setResizable(false);
            jTableListaMedico.getColumnModel().getColumn(2).setResizable(false);
            jTableListaMedico.getTableHeader().setReorderingAllowed(false);
            jTableListaMedico.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        }

    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    public void listaNome() {
        Vector<Medico> listaNomes = medicoDAO.mostraTodos();
        Vector conjuntoLinhas = new Vector();

        for (Medico md : listaNomes) {
            Vector linha = new Vector();

            linha.add(md.getNome());
            linha.add(md.getCrm());
            linha.add(md.getEspecialidade());

            conjuntoLinhas.add(linha);

        }
        Vector conjuntoColunas = new Vector();
        conjuntoColunas.add("NOME");
        conjuntoColunas.add("CRM");
        conjuntoColunas.add("ESPECIALIDADE");

        DefaultTableModel tabela = new DefaultTableModel(conjuntoLinhas, conjuntoColunas);

        jTableListaMedico.setModel(tabela);

        jTableListaMedico.getColumnModel().getColumn(0).setResizable(false);
        jTableListaMedico.getColumnModel().getColumn(1).setResizable(false);
        jTableListaMedico.getColumnModel().getColumn(2).setResizable(false);
        jTableListaMedico.getTableHeader().setReorderingAllowed(false);
        jTableListaMedico.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }


    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jComboBoxEspecialidade.setSelectedIndex(-1);
        jTextFieldidMedico.setText("");
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");

        jFormattedTextFielCpf.setText("");
        jFormattedTextFieldCelular.setText("");
        jFormattedTextFieldCrm.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelefone.setText("");

        jTextFieldNome.setEnabled(false);
        jTextFieldEmail.setEnabled(false);

        jFormattedTextFielCpf.setEnabled(false);
        jFormattedTextFieldCelular.setEnabled(false);
        jFormattedTextFieldCrm.setEnabled(false);
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jComboBoxEspecialidade.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);


    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldidMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidMedicoActionPerformed


    }//GEN-LAST:event_jTextFieldidMedicoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        String message = "Voce deseja realmente  excluir?";

        int reply = JOptionPane.showConfirmDialog(null, message, "", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            medico.setIdMedico(Integer.parseInt(jTextFieldidMedico.getText()));
            medicoDAO.excluir(medico);
            jComboBoxEspecialidade.setSelectedIndex(-1);
            jTextFieldidMedico.setText("");
            jTextFieldNome.setText("");
            jTextFieldEmail.setText("");
            jFormattedTextFielCpf.setText("");
            jFormattedTextFieldCelular.setText("");
            jFormattedTextFieldCrm.setText("");
            jFormattedTextFieldRg.setText("");
            jFormattedTextFieldTelefone.setText("");

            jTextFieldNome.setEnabled(false);
            jTextFieldEmail.setEnabled(false);
            jFormattedTextFielCpf.setEnabled(false);
            jFormattedTextFieldCelular.setEnabled(false);
            jFormattedTextFieldCrm.setEnabled(false);
            jFormattedTextFieldRg.setEnabled(false);
            jFormattedTextFieldTelefone.setEnabled(false);
            jComboBoxEspecialidade.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            TelaFormularioMedico tela = new TelaFormularioMedico();
            tela.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableListaMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaMedicoMouseClicked
        if (jTableListaMedico.getSelectedRow() >= 0) {
            String nome = "" + jTableListaMedico.getModel().getValueAt(jTableListaMedico.getSelectedRow(), 0);
            medicoDAO.acessaTabela(medico, nome);
            jTextFieldidMedico.setText(String.valueOf(medico.getIdMedico()));
            jFormattedTextFieldCrm.setText(medico.getCrm());
            jTextFieldNome.setText(medico.getNome());
            jFormattedTextFieldRg.setText(medico.getRg());
            jFormattedTextFielCpf.setText(medico.getCpf());
            jComboBoxEspecialidade.setSelectedItem(medico.getEspecialidade());
            jTextFieldEmail.setText(medico.getEmail());
            jFormattedTextFieldTelefone.setText(medico.getTelefone());
            jFormattedTextFieldCelular.setText(medico.getCelular());

            jButtonEditar.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonSalvar.setEnabled(false);
        }

    }//GEN-LAST:event_jTableListaMedicoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFormularioMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEspecialidade;
    private javax.swing.JFormattedTextField jFormattedTextFielCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldCrm;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaMedico;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldidMedico;
    // End of variables declaration//GEN-END:variables
}
